#!/bin/sh

# Create the user and switch to user
read -p "Pick a username: " username
useradd -m $username
echo "Now pick a password"
passwd $username
echo "Log in as your new username!"
su $username

# cd to /home/$username and create some directories
cd /home/$username
mkdir Documents
mkdir Downloads

# Acticate multilib
sudo vim /etc/pacman.conf +"g/\#\[multilib\]/normal 0xjx" +wq

# Set pacman.conf options
sudo vim /etc/pacman.conf +"g/\#Color/normal 0xOILoveCandy" +wq

# Sync time
sudo timedatectl set-ntp true

# Update and install pacman-contrib
sudo pacman -Syu
sudo pacman -S pacman-contrib

# Update mirrorlist
echo "Updating mirror list... one moment please"
sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/TheRealYougCraft/personal-scripts/master/mirrorlist-update)"

# Install packages
sudo pacman -S $(curl -fsSL https://raw.githubusercontent.com/TheRealYougCraft/personal-scripts/master/install_packages)
nvidia-modprobe

# Specify Laptop or desktop
python -c "$(curl -fsSl https://raw.githubusercontent.com/TheRealYougCraft/personal-scripts/master/desktop_or_laptop)" $username

# Install scripts repo
git clone https://github.com/TheRealYougCraft/personal-scripts /home/$username/scripts
chmod +x /home/$username/scripts/*

# Make config dir
mkdir -p /home/$username/.config

# Clone dotfiles repo
git clone https://github.com/TheRealYougCraft/dotfiles /home/$username/dotfiles

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git /home/$username/.vim/bundle/Vundle.vim

# Install bumblebee-status for i3-gaps
git clone https://github.com/tobi-wan-kenobi/bumblebee-status /home/$username/.config/bumblebee-status

# Install yay
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay

# Install AUR packages
yay -S $(curl -fsSL https://raw.githubusercontent.com/TheRealYougCraft/personal-scripts/master/aur_install)

# Install Oh-My-Zsh!
export ZSH=/home/$username/.oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Remove any old configs
sudo rm -f .zshrc .vimrc .tmux.conf

# Export config files
mkdir -p /home/$username/.config/i3/
mkdir -p /home/$username/.config/alacritty/
sudo mkdir -p /etc/X11/xorg.conf.d/
sudo python /home/$username/dotfiles/export.py $username

# Set default shell to zsh
chsh -s /bin/zsh

# Install Vundle Plugins
vim +PluginInstall +qall

# Install bumblebee-status module dependencies
sudo python -m pip install psutil

# Fix Discord crackling
sudo vim /etc/pulse/default.pa +"g/load-module module-udev-detect/normal A tsched=0" +wq

# Make grub config
sudo sh /home/$username/scripts/grub-update

# Enable services
sudo systemctl enable lightdm
sudo systemctl enable NetworkManager

# Make nvidia X11 config
sudo nvidia-xconfig

# Set up cronjobs
sudo systemctl enable cronie
sudo systemctl start cronie
crontab ~/.crontab
sudo crontab ~/.sudocron

# Inform the user
echo "Restart your terminal for more changes to take effect!"
echo "Remember to set up the following:

- X (check /etc/X11/xorg.conf)
- lightdm
- lightdm-mini-greeter
- lxappearance

Additionally:
Change the workspace monitor
assignments in ~/dotfiles/config if you
have a multi-monitor setup.
Remember to always make changes in the
git repos by using either 'dotfl' or 'scpt'
to pull changes first. Then for changed dotfiles
you can run suexport.

All changes will take effect on reboot."
